language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
  - "nightly"
# command to install dependencies
install:
  - pip install -e ".[testing]"
# command to run tests
script:
  - py.test # or py.test for Python versions 3.5 and below
services:
  - mysql


before_script:
- mysql -u root -e 'CREATE DATABASE flaxgame;'
- mysql -u root -e "CREATE USER 'flaxgame'@'localhost' IDENTIFIED BY '*Flax*Game*2017*;';"
- mysql -u root -e "GRANT ALL ON flaxgame.* TO 'flaxgame'@'localhost';"
- initialize_flax_db development.ini

# Because Travis CI doesn't currently support Discord (They should soon though, check https://github.com/travis-ci/travis-tasks/pull/71)
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
